server:
  port: 8083
spring:
  application:
    name: hystrix-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 自定义服务名称信息
    instance-id: hystrix-provider:8083
    #访问路径可以显示Ip地址
    prefer-ip-address: true

info:
  app.name: study-springcloud
  company.name: www.ff.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
