server:
  port: 8761
eureka:
  instance:
    # eureka注册中心的实例名称
    hostname: localhost
  client:
    # false表示不想注册中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址（查询和注册服务）
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
