eureka:
  instance:
    # eureka注册中心的实例名称
    hostname: eureka8761
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址（查询和注册服务）
#      defaultZone: http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/
      defaultZone: http://localhost:8761/eureka/
