server:
  port: 8092
  servlet:
    context-path: /feign
eureka:
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: consumer-feign
