server:
  port: 8090
  servlet:
    context-path: /consumer
eureka:
  client:
    # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-consumer
