server:
  port: 8080
spring:
  application:
    # 对应的微服务名字（eureka会自动改为全大写）
    name: eureka-provider
  profiles:
    active: provider8080

info:
  app.name: study-springcloud
  company.name: www.ff.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
