eureka:
  client:
    service-url:
      #      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 自定义服务名称信息
    instance-id: eureka-provider:8080
    #访问路径可以显示Ip地址
    prefer-ip-address: true
