server:
  port: 8092
  servlet:
    context-path: /feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: ${server.servlet.context-path}/info
    health-check-url-path: ${server.servlet.context-path}/health
spring:
  application:
    name: consumer-feign
